version: '3'

services:
  thumbor1:
    image: ghcr.io/minimalcompact/thumbor:latest
    volumes:
      - thumbor_cache:/data
    environment:
      - THUMBOR_PORT=8888
      - SECURITY_KEY=george
      - MAX_AGE=15724800  # 182 days
      - AUTO_WEBP=True
      - QUALITY=80
      # - AUTO_AVIF=True
      - ALLOW_UNSAFE_URL=False
    restart: always

  thumbor2:
    image: ghcr.io/minimalcompact/thumbor:latest
    volumes:
      - thumbor_cache:/data
    environment:
      - THUMBOR_PORT=8888
      - SECURITY_KEY=george
      - MAX_AGE=15724800  # 182 days
      - AUTO_WEBP=True
      - QUALITY=80
      # - AUTO_AVIF=True
      - ALLOW_UNSAFE_URL=False
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "888:80"
    depends_on:
      - thumbor1
      - thumbor2
    restart: always

volumes:
  thumbor_cache:
